### PR TITLE
Merge master, part 3

### PR DESCRIPTION
**Pull request by monoidal**

### CODE REVIEW

**Comment by aspiwack** [comment]
After merging with #172 , I can see these warnings (I don't know whether they were here before):

```
WARNING: file compiler/coreSyn/CoreUtils.hs, line 297
  Trying to coerce ($WEq#
                      @ k0_a30T @ a_a30U @ a_a30U @~ (<a_a30U>_N :: a_a30U ~# a_a30U)
  :: (a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)
  ((~) <k0_a30T>_N <a_a30U>_N (Sym co_a30Y))_R
  (a_a30U ~ a_a30U) ~R# (a_a30U ~ b_a30V)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/coreSyn/CoreUtils.hs:293:273 in ghc:CoreUtils
        mkCast, called at compiler/simplCore/SimplUtils.hs:331:42 in ghc:SimplUtils
WARNING: file compiler/coreSyn/CoreUtils.hs, line 297
  Trying to coerce ($WEq#
                      @ k0_a30T @ a_a30U @ a_a30U @~ (<a_a30U>_N :: a_a30U ~# a_a30U)
  :: (a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)
  ((~) <k0_a30T>_N <a_a30U>_N (Sym co_a30Y))_R
  (a_a30U ~ a_a30U) ~R# (a_a30U ~ b_a30V)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/coreSyn/CoreUtils.hs:293:273 in ghc:CoreUtils
        mkCast, called at compiler/simplCore/SimplUtils.hs:331:42 in ghc:SimplUtils
WARNING: file compiler/coreSyn/CoreUtils.hs, line 297
  Trying to coerce ($WEq#
                      @ k0_a30T @ a_a30U @ a_a30U @~ (<a_a30U>_N :: a_a30U ~# a_a30U)
  :: (a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)
  ((~) <k0_a30T>_N <a_a30U>_N (Sym co_a30Y))_R
  (a_a30U ~ a_a30U) ~R# (a_a30U ~ b_a30V)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/coreSyn/CoreUtils.hs:293:273 in ghc:CoreUtils
        mkCast, called at compiler/simplCore/SimplUtils.hs:331:42 in ghc:SimplUtils
WARNING: file compiler/coreSyn/CoreUtils.hs, line 297
  Trying to coerce ($WEq#
                      @ k0_a30T @ a_a30U @ a_a30U @~ (<a_a30U>_N :: a_a30U ~# a_a30U)
  :: (a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)
  ((~) <k0_a30T>_N <a_a30U>_N (Sym co_a30Y))_R
  (a_a30U ~ a_a30U) ~R# (a_a30U ~ b_a30V)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/coreSyn/CoreUtils.hs:293:273 in ghc:CoreUtils
        mkCast, called at compiler/simplCore/SimplUtils.hs:331:42 in ghc:SimplUtils
WARNING: file compiler/coreSyn/CoreUtils.hs, line 297
  Trying to coerce ($WEq#
                      @ k0_a30T @ a_a30U @ a_a30U @~ (<a_a30U>_N :: a_a30U ~# a_a30U)
  :: (a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)
  ((~) <k0_a30T>_N <a_a30U>_N (Sym co_a30Y))_R
  (a_a30U ~ a_a30U) ~R# (a_a30U ~ b_a30V)
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/coreSyn/CoreUtils.hs:293:273 in ghc:CoreUtils
        mkCast, called at compiler/specialise/Specialise.hs:870:19 in ghc:Specialise
```

**Comment by aspiwack** [comment]
Note that it means that `Eq#` still has a wrapper.

**Comment by aspiwack** [comment]
Well, the `Eq#` wrapper may be unnecessary, but it shouldn't be a problem: `Eq#` is a regular data constructor for the type class `~`. Not an unlifted data constructor.

**Comment by aspiwack** [comment]
I more or less know what's happening here: there is one application missing. The last application (the coercion) is taken as a type, even though it is supposed to be a dictionary. Hence the type `(a_a30U ~# <a_a30U>_N) => a_a30U ~ <a_a30U>_N)` which should really be `a_a30U ~ a_a30U`. And I think I know why it's happening: the reason is that the wrapper for `Eq#` has an extra argument for the multiplicity. But at some place, this is manually instantiated, and a parameter is missing. It probably also explains the panic: there is a beta reduction where a type variable is substituted by a coercion. And this is asserted to be forbidden.

The fix is probably either to find the place where the instantiation occurs and add an argument, or remove wrappers for type classes.

**Comment by aspiwack** [comment]
This last commit should solve the panic. Let's see if CI is actually green.

**Comment by monoidal** [comment]
Done in #162.

**Pull request closed without merging**
