### PR TITLE
WIP: Tweag/circleci macos

### PR DESCRIPTION
**Pull request by zimbatm**

### CODE REVIEW

**Comment by aspiwack** [comment]
@zimbatm @Fuuzetsu @mrkkrp what is the status of this?

**Comment by Fuuzetsu** [comment]
I think it was blocked on build breakage on OSX that was GHC fault rather than us doing something wrong. I'd rebase and try agaiagain and take that as the current state.

**Comment by aspiwack** [comment]
I guess the question is: was is superseeded by something? Are we still planing to work on this in the future? Is it on hold?

**Comment by monoidal** [comment]
Closing, as we no longer use circleci.

**Pull request closed without merging**
